version: '3'
services: 
  rabbitmq:
    image: "rabbitmq:3-management"
    ports: 
      - "5672:5672"
      - "15672:15672"
  blockchain_listener:
    build: . 
    volumes:
      - data:/data
    env_file:
      - .env
    links:
      - "rabbitmq:rabbitmq"
    depends_on:
      - rabbitmq
    command: ./wait-for-it.sh rabbitmq:5672 -- ./BlockchainListener
  payment_listener:
    build: . 
    volumes:
      - data:/data
    env_file:
      - .env
    links:
      - "rabbitmq:rabbitmq"
    depends_on:
      - rabbitmq
    command: ./wait-for-it.sh rabbitmq:5672 -- ./PaymentListener
volumes:
  data:
