version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  stellar:
    build: .
    volumes:
      - data:/data
    env_file:
      - .env
    links:
      - "rabbitmq:rabbitmq"
    depends_on:
      - rabbitmq
    command: ./wait-for-it.sh rabbitmq:5672 -- ./main
  stellar_payments:
    build: .
    volumes:
       - data:/data
    env_file:
      - .env
    links: 
      - "rabbitmq:rabbitmq"
    depends_on:
      - rabbitmq
    command: ./wait-for-it.sh rabbitmq:5672 -- ./receive.go
volumes:
  data:
