version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run 
         name: Docker Build
         command: docker-compose build
      - run 
         name: Unit Tests
         command: docker-compose run main go test
      - run 
         name: Docker login
         command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Push Docker image to repo
          command: |
            docker tag project_stellar:latest ${DOCKER_REPO}/project_stellar:latest
            docker push ${DOCKER_REPO}/project_stellar:latest
            docker tag project_stellar:latest ${DOCKER_REPO}/project_stellar:${CIRCLE_SHA1}
            docker push ${DOCKER_REPO}/project_stellar:${CIRCLE_SHA1}

